services:
  mage_server:
    #image: mageai/mageai:latest
    build:
      context: .
      args:
        MAGE_PROJECT_NAME: ${MAGE_PROJECT_NAME}
        MAGE_CODE_PATH: ${MAGE_CODE_PATH}
        USER_CODE_PATH: ${USER_CODE_PATH}
    container_name: mageai_npm
    volumes:
      - .:/home/src/
    env_file:
      - .env
    #command: mage start ${MAGE_PROJECT_NAME}
    restart: on-failure:5
    stdin_open: true # used for interactive debugging
    tty: true # used for interactive debugging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.${PROJECT_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
    networks:
      - default

networks:
  default:
    name: pm-web
    external: true
